name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleDebug && find app/build/outputs
    - name: Upload apk
      uses: actions/upload-artifact@v1
      with:
        name: app-common-armeabi-v7a-debug.apk
        path: app/build/outputs/apk/common/debug/app-common-armeabi-v7a-debug.apk
#         name: app-armeabi-v7a-release-unsigned.apk
#         path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk
    - name: Release APK
      # You may pin to the exact commit or the version.
      # uses: ShowMeThe/github_action_release@c03188563c3286ccd20cf0d2b1413a134e3cabc9
      uses: ShowMeThe/github_action_release@v0.01
